global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "my-project"

scrape_configs:
  - job_name: "prometheus"
    metrics_path: /metrics
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: sql_exporter
    static_configs:
      - targets: ["sql_exporter:9399"]

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ["postgres_exporter:9187"]