# Global settings and defaults. Examples https://github.com/burningalchemist/sql_exporter/blob/master/documentation/sql_exporter.yml
global:
  scrape_timeout_offset: 500ms
  min_interval: 60s
  max_connections: 3
  max_idle_connections: 3
  max_connection_lifetime: 10m

jobs:
  - job_name: netflix_db
    collectors:
      - netflix*
    enable_ping: true
    static_configs:
        - targets:
            pg1: 'postgres://pguser:pgpassword@db/netflix?sslmode=disable'
            # pg2: 'postgres://db2@127.0.0.1:25432/testdb?sslmode=disable'

collector_files:
  - "/collectors/*.collector.yml"